cli/main.c
src/token.c
src/token.h
src/tokenizer.c

```
$ valgrind ./cli/mmrbc test/fixtures/wifi.rb 1> /dev/null
==2928== Memcheck, a memory error detector
==2928== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2928== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==2928== Command: ./cli/mmrbc test/fixtures/wifi.rb
==2928== 
==2928== 
==2928== HEAP SUMMARY:
==2928==     in use at exit: 14,492 bytes in 548 blocks
==2928==   total heap usage: 90,858 allocs, 90,310 frees, 7,107,900 bytes allocated
==2928== 
==2928== LEAK SUMMARY:
==2928==    definitely lost: 80 bytes in 17 blocks
==2928==    indirectly lost: 14,412 bytes in 531 blocks
==2928==      possibly lost: 0 bytes in 0 blocks
==2928==    still reachable: 0 bytes in 0 blocks
==2928==         suppressed: 0 bytes in 0 blocks
==2928== Rerun with …
```

Reduce memory leak of Tokens

---

.gitmodules
Makefile
cli/Makefile
cli/main.c
src/Makefile
src/common.c
src/common.h
src/debug.h
src/mmrbc.h
src/token.c
src/token.h
src/tokenizer.c

- Submodule mrubyc
- Use `mrbc_raw_alloc` and `mrbc_raw_free`
- Able to select mrbc_raw_alloc or malloc by `CFLAGS=-DMRBC_ALLOC_LIBC`
- Fix memory leak

Mrubyc integrate

---

cli/main.c
src/generator.c
src/generator.h
src/scope.c
src/scope.h

- When it can be freed? - after creating mrb->vmCode
- When it can be freed? - at freeing code_snippet
- When it can be freed? - after memcpy in `Generator_generate()`
- It may need to change API of `flattenCode()` to be understandable
- ~~When it can be freed? - after used it in driver(compiler, REPL, etc.)~~
- get rid of the struct
- When it can be freed? - after using it
- When it can be freed? - at finishing the whole program
- When it can be freed? - at freeing scope
- When it can be freed? - at freeing scope

Fix memory leaks in Generator

---

cli/main.c
src/common.c
src/mmrbc.h
statistics/.gitignore

`./cli/mrbc test/fixture/hello_world.rb`
```
[INFO]  file : common.c, line : 20, func : print_memory,
Memory total:65532, used:10720, free:54812, fragment:6
(......)
[INFO]  file : common.c, line : 20, func : print_memory,
Memory total:65532, used:14596, free:50936, fragment:4
Parse has completed successfully.
[1, 
[10, 
[13], 
[2, 
[14, "puts"], 
[7, 
[6, 
[5], 
[11, 
[3, 
[4], 
[15, "Hello World!"], 
[INFO]  file : common.c, line : 20, func : print_memory,
Memory total:65532, used:14664, free:50868, fragment:4
(......)
[INFO]  file : common.c, line : 20, func : print_memory,
Memory total:65532, used:16752, free:48780, fragment:4          # Peak
(......)
[INFO]  file : common.c, line : 20, func : print_memory,
Memory total:65532, used:10500, free:55032, fragment:6
[INFO]  file : …
```

Use mrbc_init_alloc() instead of mrbc_init()

---

src/compiler.c
src/tokenizer.c

- [SOLVED] tokenizer ignores a token if it is not valid
- [TENTATIVE!] avoid SEVG by leaving memory leak
- https://github.com/hasumikin/mmruby/compare/fallback_parse_failure?expand=1#diff-6c198db2860ea5d7abc9160b828f6c8dR57

Fallbacks when parse failed

---

src/generator.c
src/scope.c
src/scope.h

Improve IREP

---

Makefile
src/Makefile
src/node.h
src/ruby-lemon-parse/parse_header.h

When we build psoc5lp_lib, we can't run the binary on the host machine, so we can't check the size of void *.
So, I worked around this by defining PTR_SIZE in the docker_psoc5lp_lib target of make.

fix: fix for building docker_psoc5lp_lib target

---

build_config/r2p2-bin.rb
mrbgems/picoruby-prk-keyboard/mrbgem.rake
mrbgems/picoruby-prk-keyboard/mrblib/keyboard.rb
mrbgems/picoruby-prk-keyboard/sig/keyboard.rbs
mrbgems/picoruby-prk-rgb/mrbgem.rake
mrbgems/picoruby-prk-rgb/mrblib/rgb.rb
mrbgems/picoruby-prk-rgb/sig/rgb.rbs
mrbgems/picoruby-prk-via/mrblib/via.rb
mrbgems/picoruby-prk-via/sig/via.rbs
mrbgems/picoruby-task-ext/mrbgem.rake
mrbgems/picoruby-task-ext/mrblib/task.rb
mrbgems/picoruby-task-ext/sig/task.rbs
mrbgems/prk_firmware.gembox

- Redesign Task class like Thread class in CRuby
- PRK stops using Task. Uses directly Sandbox instead

Redesign Task class 

---

.github/workflows/c-cpp.yml

GitHub is [planning to upgrade to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Versions prior to actions/checkout v3 use an outdated version of node, so we will upgrade to actions/checkout v4, where [Node 20 is the default](https://github.com/actions/checkout/releases/tag/v4.0.0).

Bump actions/checkout

---

build_config/r2p2-cortex-m0plus.rb
build_config/r2p2_w-cortex-m0plus.rb
mrbgems/picoruby-rng/include/rng.h
mrbgems/picoruby-rng/mrbgem.rake
mrbgems/picoruby-rng/mrblib/rng.rb
mrbgems/picoruby-rng/ports/rp2040/rng.c
mrbgems/picoruby-rng/sig/rng.rbs
mrbgems/picoruby-rng/src/rng.c

The RNG mrbgem implements generation of random numbers and strings. The main purpose of this is to generate random keys for cryptographic operations.
The API of the gem looks like the following:
- `RNG.random_int`: generates a 32-bit random integer.
- To limit the range of generated numbers, use the `%` operator to get the residual.
- `RNG.random_string(length)`: generates a string of length `length` with random bytes.
This gem currently has an implementation for RP2040 that uses RP2040's Ring Oscillator (-> https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf, Section 2.17).

Random Number Generator

---

build_config/r2p2-cortex-m0plus.rb
build_config/r2p2_w-cortex-m0plus.rb

When building R2P2 on macOS, the following error was encountered:
```
arm-none-eabi-gcc: error: unrecognized command-line option '-Wzero-length-array'; did you mean '-Wzero-length-bounds'?
```
This issue was caused by Toolchain#guess referencing RUBY_PLATFORM and selecting clang.
https://github.com/picoruby/picoruby/blob/0a5292893de2ef4088f105ed2b1c7fd42acdb4e5/lib/mruby/build.rb#L27
Therefore, I fixed it to explicitly specify `gcc` for cross-building.
----
Additionally, to successfully build R2P2 on macOS, you need to install another tool.
I am planning to submit a Pull Request to add this information to the R2P2 README.
https://github.com/picoruby/R2P2/pull/10

Fixed no compilers other than gcc are used for cross-building.

---

README.md

Because there is a possibility of an ssl-related error occurring when building on MacOS,we have added an explanation to prevent this.

add description for build on macOS

---

mrbgems/picoruby-time-class/src/time.c

When building `mruby-time-class` with ESP-IDF, a build error occurred due to referencing `_timezone`.  
ESP-IDF defines the variable `timezone` instead of `_timezone`, causing an undefined reference error during compilation.  
I modified the implementation to handle `timezone` in the same way as when `MRBC_USE_HAL_POSIX` is defined. This resolves the build error when using ESP-IDF.  
- [ESP-IDF System Time Documentation](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/system_time.html)

Fix Build Error in `mruby-time-class` When Using ESP-IDF

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb
mrbgems/picoruby-env/ports/esp32/env.c
mrbgems/picoruby-filesystem-fat/ports/esp32/flash_disk.c
mrbgems/picoruby-io-console/ports/esp32/io-console.c
mrbgems/picoruby-machine/ports/esp32/machine.c
mrbgems/picoruby-time-class/src/time.c

Added Build Configuration for ESP32 in PicoRuby
I have added build configurations for ESP32 in PicoRuby.
With this change, PicoRuby can be built as a component for ESP-IDF using [this repository](https://github.com/yuuu/picoruby-esp32), which I have made public.
- Confirmed that the Shell launches successfully on ESP32-C3 (RISC-V) and ESP32 (Xtensa).
- The reference implementation project is available [here](https://github.com/yuuu/espicoruby).
- We have a roadmap for picoruby-esp32
- https://github.com/yuuu/picoruby-esp32/issues/8
- For the current status, please check the link above.

Run PicoRuby on ESP32.

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb
mrbgems/picoruby-filesystem-fat/ports/esp32/flash_disk.c

Porting picoruby-filesystem-fat to ESP32.
I have checked the operation on Flash Disk.
SD Disc and MSC Disk are not supported.
Therefore, if you want to write your .rb or .mrb to a Flash Disk, you must do so via ESP-IDF.

Add FAT FileSystem on ESP32

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb

Added because picoruby update requires `alloc_libc: false` to be specified in the build config for ESP32.

Disable alloc_libc in ESP build config.

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb
mrbgems/picoruby-gpio/ports/esp32/gpio.c

I have added picoruby-gpio which works with ESP32.
- It is available as per the following documentation
- https://picoruby.github.io/GPIO.html
- open_drain is not yet supported
- set_function will be considered when implementing I2C, SPI, UART, PWM, etc. in the future.

Added picoruby-gpio working with ESP32.

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb

MRC_CUSTOM_ALLOC is now no longer needed; it was left in ESP32's build_config and should be removed.

Remove MRC_CUSTOM_ALLOC from build_config for esp32.

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb
mrbgems/picoruby-adc/ports/esp32/adc.c

Ported picoruby-adc so that ADC can be used with ESP32.
I use ADC Oneshot Mode Driver of ESP-IDF.
https://docs.espressif.com/projects/esp-idf/en/v5.4/esp32/api-reference/peripherals/adc_oneshot.html

Add ADC for ESP32.

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb
mrbgems/picoruby-rng/ports/esp32/rng.c

I ported picoruby-rng, which provides RNG (Random Number Generation), to the ESP32.

Add RNG for ESP32.

---

mrbgems/picoruby-adc/ports/esp32/adc.c
mrbgems/picoruby-spi/ports/esp32/spi.c

I noticed that builds for the ESP32-C3 were failing and made two corrections:
- The constant `ADC_DIGI_CLK_SRC_PLL_F160M` was undefined for ESP32-C3.
- By changing how the struct is declared, referencing this constant became unnecessary.
- The definition `SPI3_HOST` was also undefined for ESP32-C3.
- Added a conditional check for undefined cases, referencing [this implementation in esp-idf](https://github.com/espressif/esp-idf/blob/5c51472e82a58098dda8d40a1c4f250c374fc900/components/esp_driver_spi/src/gpspi/spi_master.c#L247).

Fixed build errors in ESP32C3 for adc and spi.

---

mrbgems/picoruby-shell/shell_executables/_path.txt

While attempting to build PicoRuby for the R2P2-ESP32, I encountered an error.
To address this, I have added the necessary commands to _path.txt.

Add /bin/nmble and /bin/nmcli to _path.txt

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb
mrbgems/picoruby-watchdog/ports/esp32/watchdog.c

Porting for ESP32 with Watchdog support.
On ESP32, only the following methods are supported
- Watchdog.enable
- Watchdog.disable
- Watchdog.update

Add Watchdog for ESP32.

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb
mrbgems/picoruby-adafruit_sk6812/mrbgem.rake
mrbgems/picoruby-adafruit_sk6812/mrblib/sk6812.rb
mrbgems/picoruby-rmt/include/rmt.h
mrbgems/picoruby-rmt/mrbgem.rake
mrbgems/picoruby-rmt/mrblib/rmt.rb
mrbgems/picoruby-rmt/ports/esp32/rmt.c
mrbgems/picoruby-rmt/src/rmt.c

I added an mrbgem to control the full-color LED on the M5Stamp C3 Mate.
(Product reference: https://www.switch-science.com/products/7474?srsltid=AfmBOoq09F00EjRLdsH-DWmjrZRYf34pyjhr82EakuQykOLfTpmX6DtX)
The LED uses an adafruit_sk6812 chip, which requires communication via RMT (Remote Control).
On the ESP32, this can be achieved using the following functionality:
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/rmt.html
Based on this, I have added a SK6812 class.

Add RMT for ESP32.

---

mrbgems/picoruby-adc/ports/esp32/adc.c
mrbgems/picoruby-io-console/ports/esp32/io-console.c
mrbgems/picoruby-machine/ports/esp32/machine.c
mrbgems/picoruby-rng/ports/esp32/rng.c

I made modifications to make ESP32-R2P2 work with the current `master` branch.
- For `io-console.c`, I used the one from the RP2040 implementation.
- For `Machine_stack_usage`, I’m considering using `uxTaskGetStackHighWaterMark` to implement it, but it is currently unimplemented.
- `Machine_set_hwclock` and `Machine_get_hwclock` will be implemented after SNTP support is added.

Make it buildable for ESP32 with the latest master branch where MicroRuby has been merged.

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb
mrbgems/picoruby-mbedtls/ports/esp32/timing_alt.c

I want to enable R2P2-ESP32 to connect to Wi-Fi.
To do this, I first added mrbgems to get nmcli working.
I ported the files in the ports directory of mbedtls to ESP32.
However, this function does not seem to be used.

Add mrbgems for nmcli to esp32 build config.

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb
mrbgems/picoruby-uart/ports/esp32/uart.c

Porting picoruby-uart for ESP32.
I have already confirmed that echo works using M5Stamp C3 (ESP32-C3) and CP2102, connecting from a terminal on a PC.
```ruby
require 'uart'
uart = UART.new(unit: 'ESP32_UART1', txd_pin: 19, rxd_pin: 18)
loop do
str = uart.read
unless str.nil?
uart.write(str)
end
sleep_ms(10)
end
````

Add UART for ESP32.

---

mrbgems/picoruby-rmt/ports/esp32/rmt.c

This PR modifies the ESP32 port of the picoruby-rmt library to replace floating-point operations with integer arithmetic in the RMT encoder callback function.
On ESP32, performing floating-point arithmetic inside interrupt context (such as RMT encoder callbacks) can lead to a Coprocessor exception (Guru Meditation Error). This occurs because the FPU context is not preserved during interrupt execution.
For example, the following runtime error was observed:
```
Guru Meditation Error: Core  0 panic'ed (Coprocessor exception). 
EXCCAUSE: 0x00000004
Backtrace: 0x4010ebd6:0x3ffb1ac0 ...
```
This error indicates that floating-point operations in the encoder_callback function caused a crash. To prevent such runtime crashes, floating-point arithmetic was replaced with integer-based calculations.
- …

Avoid float in RMT timing calculation to prevent FPU exception on ESP32

---

mrbgems/picoruby-watchdog/ports/esp32/watchdog.c

Added reboot command functionality to ESP32 platform by implementing the `Watchdog_reboot()` function.
This enables ESP32 to also support reboot from shell.
https://github.com/user-attachments/assets/6aa79c17-9f7c-4799-9dd6-cd200149c38c
https://github.com/user-attachments/assets/5ec09400-5f5b-4c2f-a662-92ab503392a1

Enable reboot command support for ESP32 platform

---

mrbgems/picoruby-mbedtls/mrblib/cmac.rb
mrbgems/picoruby-mbedtls/src/mruby/cmac.c

An error occurs when running the following sample program on a Raspberry Pi Pico2 with MicroRuby:
```ruby
require 'mbedtls'
key = 'thisisasecretkey'
cmac = MbedTLS::CMAC.new(key, 'aes')
data = 'Hello, World!'
cmac.update(data)
puts cmac.digest
```
The error message is as follows:
```
undefined method '_init_aes' for Class (undefined method '_init_aes' for Class)
```
`MbedTLS::CMAC.new` calls `self._init_aes`, but at that time, `self` refers to `Class`.  
This fix changes `_init_aes` to be a singleton method so that it can be called properly from `self.new`.

Fix error when using MbedTLS::CMAC.new on mruby.

---

mrbgems/peripherals.gembox
mrbgems/picoruby-gpio/mrblib/gpio.rb
mrbgems/picoruby-gpio/sig/gpio.rbs
mrbgems/picoruby-irq/README.md
mrbgems/picoruby-irq/example/irq_gpio.rb
mrbgems/picoruby-irq/include/irq.h
mrbgems/picoruby-irq/mrbgem.rake
mrbgems/picoruby-irq/mrblib/irq.rb
mrbgems/picoruby-irq/ports/rp2040/irq.c
mrbgems/picoruby-irq/sig/irq.rbs
mrbgems/picoruby-irq/src/irq.c
mrbgems/picoruby-irq/src/mruby/irq.c
mrbgems/picoruby-irq/src/mrubyc/irq.c

This pull request introduces a new IRQ (Interrupt Request) subsystem for PicoRuby, enabling asynchronous event handling for GPIO pins and other peripherals. It adds a new `picoruby-irq` gem, complete with Ruby and C APIs, documentation, type signatures, and an example. Additionally, it enhances the GPIO API with IRQ support and makes some minor improvements to type signatures.
**Key changes:**
* Added the `picoruby-irq` gem, providing IRQ (interrupt) support for GPIO and peripherals, including C and Ruby implementations, documentation (`README.md`), and an example (`example/irq_gpio.rb`). This includes debouncing, event queueing, and IRQ management APIs. [[1]](diffhunk://#diff-29ed617c4f8c245402bf53effe5797c85b92e566972ae9fe1b823a20d3097788R1-R112) …

IRQ module

---

build_config/riscv-esp-microruby.rb
mrbgems/picoruby-filesystem-fat/ports/esp32/flash_disk.c
mrbgems/picoruby-machine/ports/esp32/machine.c

I ported MicroRuby to run on the ESP32 RISC-V microcontroller.
I have confirmed that the Hello world sample program runs on the M5StampC3 Mate (ESP32 RISC-V).  
The operation of mrbgems such as `picoruby-require` and `picoruby-shell` has not yet been verified.  
Operation on ESP32 Xtensa has also not been confirmed.
When building MicroRuby, the factory area size of 1MB was insufficient.  
Therefore, I expanded the factory area to 2MB.  
The same change applies when using mruby/c: the factory area on FlashROM is increased to 2MB.

Port MicroRuby to ESP32 RISC-V.

---

build_config/riscv-esp.rb
build_config/xtensa-esp.rb
mrbgems/picoruby-machine/ports/esp32/machine.c

Using the latest version of PicoRuby, I encountered build errors on [R2P2-ESP32](https://github.com/picoruby/R2P2-ESP32/) .  
To address this, I made the following two modifications:
1. Made the symbol names `hal_enable_irq` and `hal_disable_irq` configurable  
2. Disabled the use of `picoruby-irq`

Resolving ESP32 build errors with IQR.

---

build_config/r2p2-microruby-cortex-m33.rb
build_config/r2p2_w-microruby-cortex-m33.rb
mrbgems/picoruby-mruby/include/custom_ro_data.h
mrbgems/picoruby-mruby/ports/rp2040/custom_ro_data.c
mrbgems/picoruby-mruby/src/custom_ro_data.c

Add custom RO data implementation to support ROM or RAM memory distinction:
- Add `MRB_USE_CUSTOM_RO_DATA_P` and `MRB_LINK_TIME_RO_DATA_P` defines
- Implement `mrb_ro_data_p` function with platform-specific port
- Add RP2040/RP2350-specific implementation using `__etext` symbol

feat: Add custom RO data support for mruby

---

mrbgems/picoruby-sandbox/src/mruby/sandbox.c

This PR fixes that some local variable names are overwritten in `Sandbox` with mruby. This bug will occur on variable names that are inline symbols, because unpacking inline symbols uses a shared buffer (`mrb->symbuf`).
The reproduction code on IRB is below.
Before:
```
irb> v1=1
=> 1
irb> v2=2
=> 2
irb> v1
=> #<NoMethodError: undefined method 'v1' for Class>
irb> v2
=> #<NoMethodError: undefined method 'v2' for Class>
irb> local_variables
=> [:v, :"\"_\\x00\"", :_]
```
After:
```
irb> v1=1
=> 1
irb> v2=2
=> 2
irb> v1
=> 1
irb> v2
=> 2
irb> local_variables
=> [:_, :v1, :v2]
```

Fix local variable names are overwritten in `Sandbox`

---

mrbgems/picoruby-mbedtls/example/signature.md

I noticed the sample program in picoruby-mbedtls's signature.md wasn't working.
I found a typo in the code and fixed it.

Fixed a typo in picoruby-mbedtls's signature.md

---

mrbgems/picoruby-machine/include/machine.h
mrbgems/picoruby-machine/ports/rp2040/machine.c
mrbgems/picoruby-machine/sig/machine.rbs
mrbgems/picoruby-machine/src/machine.c
mrbgems/picoruby-machine/src/mruby/machine.c
mrbgems/picoruby-machine/src/mrubyc/machine.c
mrbgems/picoruby-mbedtls/src/mruby/cipher.c
mrbgems/picoruby-mbedtls/src/mrubyc/cipher.c
mrbgems/picoruby-shinonome/src/mruby/shinonome.c
mrbgems/picoruby-shinonome/src/mrubyc/shinonome.c

This commit enables dual CDC (Communications Device Class) USB ports to separate standard output and debug output on embedded platforms.
Changes:
- picoruby-machine: Add hal_write/hal_flush support for dual CDC
- Define FD_STDOUT/FD_STDERR and CDC_INSTANCE_* macros
- Route fd=1 (stdout) to CDC0, fd=2 (stderr) to CDC1
- Update debug_printf() to use stderr (fd=2)
- Add Machine.debug_puts method for Ruby code debug output
- Replace printf() with D() macro in picoruby-mbedtls and picoruby-shinonome
This allows developers to view application output on CDC0 (/dev/ttyACM0) and debug messages on CDC1 (/dev/ttyACM1) simultaneously.

Add dual CDC USB support for separate stdout and stderr

---

mrbgems/picoruby-machine/ports/esp32/machine.c

To follow #269, the picoruby-machine for ESP32 has also implemented support for separating stdout and stderr.

Separate the output of picoruby-machine for ESP32 into stdout and stderr.
