Makefile, cli/main.c, src/common.c, src/common.h, src/debug.h
- introduce NDEBUG option according as mruby/c (and lemon)
- memcheck() which finds out memory leaks
=> NDEBUG & memcheck

src/generator.c, src/node.c, src/ruby-lemon-parse/parse.y, src/ruby-lemon-parse/parse_header.h, src/scope.c, src/scope.h, src/tokenizer.c
=> if elsif else end

src/generator.c, src/ruby-lemon-parse/parse.y, src/ruby-lemon-parse/parse_header.h, src/tokenizer.c
=> Conditional Operator and dsym

src/ruby-lemon-parse/parse.y
- operation of cmdarg stack is not implemented yet
=> begin ~ end

src/compiler.c, src/generator.c, src/ruby-lemon-parse/parse.y, src/ruby-lemon-parse/parse_header.h
=> Def method with mandatory args

src/generator.c, test/fixnum_test.rb
Things like `p(0xFFFFF)` => 1048575
=> Big Fixnum other than decimal

README.md, Rakefile
https://github.com/picoruby/picoruby/issues/106
=> Fix PTR_SIZE

mrbgems/picoruby-bin-picoirb/tools/picoirb/picoirb.c, mrbgems/picoruby-bin-picoirb/tools/picoirb/sandbox.c, mrbgems/picoruby-bin-picoirb/tools/picoirb/sandbox.h, mrbgems/picoruby-bin-r2p2/tools/r2p2/r2p2.c, mrbgems/picoruby-io-console/src/io-console.c, mrbgems/picoruby-prk-joystick/include/prk-joystick.h, mrbgems/picoruby-prk-joystick/src/prk-joystick.c, mrbgems/picoruby-prk-keyboard/include/prk-keyboard.h, mrbgems/picoruby-prk-keyboard/mrblib/keyboard.rb, mrbgems/picoruby-prk-keyboard/sig/keyboard.rbs, mrbgems/picoruby-prk-keyboard/src/prk-keyboard.c, mrbgems/picoruby-prk-rgb/include/prk-rgb.h, mrbgems/picoruby-prk-rgb/src/prk-rgb.c, mrbgems/picoruby-prk-rotary_encoder/src/prk-rotary_encoder.c, mrbgems/picoruby-prk-sounder/include/prk-sounder.h, mrbgems/picoruby-prk-sounder/src/prk-sounder.c, mrbgems/picoruby-sandbox/src/sandbox.c, tasks/picogems.rake
ref https://github.com/picoruby/prk_firmware/issues/109
=> Deprecate hardware UART of PRK Firmware

mrbgems/picoruby-prk-rotary_encoder/mrblib/rotary_encoder.rb, mrbgems/picoruby-prk-rotary_encoder/sig/rotary_encoder.rbs, mrbgems/picoruby-spi/include/spi.h, mrbgems/picoruby-spi/mrblib/spi.rb, mrbgems/picoruby-spi/ports/rp2040/spi.c, mrbgems/picoruby-spi/sig/spi.rbs, mrbgems/picoruby-spi/src/spi.c
- `SPE#select` and `SPI#deselect`
- select can take a block
- Improve internal data handling
=> Fix SPI class

mrbgems/peripherals.gembox, mrbgems/picoruby-pwm/include/pwm.h, mrbgems/picoruby-pwm/mrbgem.rake, mrbgems/picoruby-pwm/mrblib/pwm.rb, mrbgems/picoruby-pwm/ports/rp2040/pwm.c, mrbgems/picoruby-pwm/sig/pwm.rbs, mrbgems/picoruby-pwm/src/pwm.c
API guideline:
https://github.com/mruby/microcontroller-peripheral-interface-guide/blob/main/mruby_io_PWM_en.md
=> PWM class / Generic IO

mrbgems/picoruby-cyw43/sig/cyw43.rbs, mrbgems/picoruby-gpio/sig/gpio.rbs, mrbgems/picoruby-music-macro-language/sig/mml.rbs, mrbgems/picoruby-prk-consumer_key/sig/consumer_key.rbs, mrbgems/picoruby-prk-keyboard/sig/keyboard.rbs, mrbgems/picoruby-prk-rgb/sig/rgb.rbs, mrbgems/picoruby-prk-rotary_encoder/sig/rotary_encoder.rbs, mrbgems/picoruby-prk-sounder/sig/sounder.rbs, mrbgems/picoruby-prk-via/sig/via.rbs, mrbgems/picoruby-require/sig/require.rbs, mrbgems/picoruby-sandbox/sig/sandbox.rbs, mrbgems/picoruby-sqlite3/sig/resultset.rbs, mrbgems/picoruby-task-ext/sig/task.rbs, mrbgems/picoruby-uart/sig/uart.rbs
ref https://github.com/picoruby/picoruby.github.io/issues/4
=> add positional args to rbs

mrbgems/picoruby-base16/sig/base16.rbs, mrbgems/picoruby-base64/sig/base64.rbs
Added the missing type signatures for Base16 and Base64.
=> Types for Base16 and Base64

mrbgems/picoruby-uart/mrblib/uart.rb
ref https://github.com/picoruby/picoruby/issues/171
=> Add warning: TXD of RP2040's uart1 doesn't work

build_config/arm-linux-gnueabihf.rb, build_config/default.rb, mrbgems/picoruby-net/mrbgem.rake
Ingrate the place where you specify the SSL and Crypto library options.
- We have confirmed that the build is successful when the build config is default.
- We have not yet confirmed the build when the build config is arm-linux-gnueabihf, as we have not yet been able to create the environment successfully.
=> Integrated ssl and crypto library flags additional code

mrbgems/picoruby-machine/ports/esp32/machine.c
I have been trying to figure out what is causing the problem of irb not being able to run on ESP32.
Finally, I found that when I ran `Sandbox.new` the main_task kept the process occupied.
This was due to the fact that the `picoruby-machine` porting for ESP32 was not ready for timer.
I have added it to solve the problem.
=> Add Timer to picoruby-machine for ESP32 to make task READY.

build_config/riscv-esp.rb, build_config/xtensa-esp.rb, mrbgems/picoruby-spi/include/spi.h, mrbgems/picoruby-spi/mrblib/spi.rb, mrbgems/picoruby-spi/ports/esp32/spi.c, mrbgems/picoruby-spi/src/spi.c
Porting for ESP32 to support SPI communication.
=> Add SPI for ESP32.

build_config/riscv-esp.rb, build_config/xtensa-esp.rb, mrbgems/picoruby-pwm/ports/esp32/pwm.c
Porting for ESP32 with PWM support.
=> Add PWM for ESP32.

mrbgems/picoruby-gpio/sig/gpio.rbs, mrbgems/picoruby-i2c/mrblib/i2c.rb, mrbgems/picoruby-i2c/sig/i2c.rbs, mrbgems/picoruby-i2c/src/mruby/i2c.c, mrbgems/picoruby-i2c/src/mrubyc/i2c.c, mrbgems/picoruby-spi/mrblib/spi.rb
=> Add timeout parameter to I2C

build_config/riscv-esp.rb, build_config/xtensa-esp.rb
Enabled the use of vim commands on ESP32.
=> Add Vim for ESP32.

mrbgems/picoruby-bin-microruby/tools/microruby/microruby.c, mrbgems/picoruby-bin-r2p2/tools/r2p2/r2p2.c, mrbgems/picoruby-mruby/example/task.rb, mrbgems/picoruby-mruby/example/task_pass.rb, mrbgems/picoruby-mruby/include/mrc_utils.h, mrbgems/picoruby-mruby/include/task.h, mrbgems/picoruby-mruby/mrblib/task.rb, mrbgems/picoruby-mruby/sig/mruby.rbs, mrbgems/picoruby-mruby/sig/task.rbs, mrbgems/picoruby-mruby/src/mrc_utils.c, mrbgems/picoruby-mruby/src/task.c, mrbgems/picoruby-mrubyc/sig/task.rbs, mrbgems/picoruby-sandbox/mrblib/sandbox.rb, mrbgems/picoruby-sandbox/sig/sandbox.rbs, mrbgems/picoruby-sandbox/src/mruby/sandbox.c, mrbgems/picoruby-sandbox/src/mrubyc/sandbox.c, mrbgems/picoruby-sandbox/src/sandbox.c, mrbgems/picoruby-shell/mrblib/shell.rb, mrbgems/picoruby-shell/shell_executables/taskstat.rb
This commit implements a comprehensive overhaul of MicroRuby's task management system with a complete Ruby Task API. Key implementations include:
- Task class API: Complete method suite including `Task.new`, `Task.stat`, `Task.current`, `Task.pass`, `join`, `suspend`, `resume`, `terminate`
- Ruby object wrapping: TCB (Task Control Block) encapsulated as Ruby objects with automatic GC memory management
- Dynamic task naming: Migration from fixed-length C strings to dynamic Ruby string objects
- Status management: Unified task status system (DORMANT, READY, RUNNING, WAITING, SUSPENDED)
- Task synchronization: Task synchronization via join method (note: circular join causes deadlock)
- Statistics system: Structured statistics information through `Task::Stat` class
- Error handling: Proper …
=> feat(task): Implement complete Ruby Task class with multitasking support

tasks/picoruby/test.rake
=> Fix a typo in test.rake

mrbgems/picoruby-filesystem-fat/ports/rp2040/flash_disk.c
Ref https://github.com/picoruby/R2P2/pull/19
Instead of customizing pico-sdk this patch will support customized rp2040js with special sysinfo platform register
=> Run custom breakpoint in rp2040js mode
